import "./globals.css";
// import "@uploadthing/react/styles.css";
import { Toaster } from "@/components/ui/toaster"
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import Provider from "@/components/Provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-full h-full">
        <Provider>
          <div className="main w-full h-full">{children}</div>
          <Toaster />
        </Provider>
      </body>
    </html>
  );
}
